url=jdbc:mariadb://127.0.0.1:3306/webshopdb
username=webshopuser
password=webshoppassword
driver=org.mariadb.jdbc.Driver
classpath=lib/mariadb-java-client-3.5.9.jar
searchPath=changelogs
changeLogFile=changelog.mariadb.sql